version: "2.3"
services:
  web:
    image: kuncie-cart
    container_name: cart_management_api
    ports:
      - 9090:9090
    depends_on:
      mysql:
        condition: service_healthy

    volumes:
      - ./config.json:/app/config.json
  mysql:
    image: mysql:5.7
    container_name: kuncie_cart_mysql
    command: mysqld --user=root
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=kuncie-cart
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
